Algoritmo "lista 2-1"

Var
   n1, n2: inteiro
Inicio
escreval ("digite um numero para se dizer se ele é par ou impar e se é positivo ou negativo: ")
escreval ("")
leia (n1)
se (n1 mod 2=0) entao
   escreval ("seu numero é par")
senao
   escreval ("seu numero é ímpar")
fimse

se (n1 > 0) entao
   escreva ("e também é positivo")
senao
   escreva ("e também é negativo")
fimse

Fimalgoritmo